### ISSUE TITLE
[BUG] Calculating Histogram fails when selecting 'StronglyEntanglingLayers'

### ISSUE THREAD

**Issue by stroblme** [cirKITers/MindTheQApp#12]
Error when using 'StronglyEntanglingLayers'.
Apparently fidelity calculation fails, thus histogram receives no update.

```
ValueError: operands could not be broadcast together with shapes (4,4) (0,4) 
```

```
Traceback (most recent call last):
  File "/home/lc3267/Documents/CodeWorkspace/Quantum-Surrogate-Project/app/pages/3-expressibility-viz.py", line 465, in update_output_probabilities
    x_samples, y_samples, z_samples = expr_sampler.sample_hist_state_fidelities(
  File "/home/lc3267/Documents/CodeWorkspace/Quantum-Surrogate-Project/app/utils/expressibility.py", line 160, in sample_hist_state_fidelities
    fidelities = self.sample_state_fidelities(bf=bf, pf=pf, ad=ad, pd=pd, dp=dp)
  File "/home/lc3267/Documents/CodeWorkspace/Quantum-Surrogate-Project/app/utils/expressibility.py", line 146, in sample_state_fidelities
    np.sqrt(sqrt_sv1 * sv[self.n_samples :] * sqrt_sv1),
  File "/home/lc3267/Documents/CodeWorkspace/Quantum-Surrogate-Project/.venv/lib/python3.10/site-packages/pennylane/numpy/tensor.py", line 155, in __array_ufunc__
    res = super().__array_ufunc__(ufunc, method, *args, **kwargs)
ValueError: operands could not be broadcast together with shapes (4,4) (0,4) 

```
![168d9e9c-2b45-42ac-8ab7-0cf0743da256](https://github.com/stroblme/Quantum-Surrogates/assets/25545736/42b28aea-4d6d-4f8c-89e2-fdb84b4dc697)

**Comment by majafranz** [comment]
This bug got fixed through using a custom implementation of the StronglyEntanglingLayers. For verification of this implementation see: #22
